services:
  cyber-chef:
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberchef
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 10 * * 1-5"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_MAIL_HOST=${SMTP}"
      - "DIUN_NOTIF_MAIL_PORT=465"
      - "DIUN_NOTIF_MAIL_SSL=true"
      - "DIUN_NOTIF_MAIL_USERNAME=${USER}"
      - "DIUN_NOTIF_MAIL_PASSWORD=${PASSWD}"
      - "DIUN_NOTIF_MAIL_FROM=${FROM}"
      - "DIUN_NOTIF_MAIL_TO=${TO}"
    labels:
            - diun.enable=true
    restart: unless-stopped