name: excalidraw
services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    ports:
      - "127.0.0.1:5000:80"
    volumes:
      - excalidraw_data:/data
      - ./config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.omv.kllnr.de`)"
      - "traefik.http.routers.excalidraw.entrypoints=websecure"
      - "traefik.http.routers.excalidraw.tls.certresolver=omv_certresolver"
volumes:
  excalidraw_data: